### ISSUE TITLE
please update ' README.MD'  curl  link

### ISSUE THREAD

**Issue by zhuang00** [HirbodBehnam/Shadowsocks-Cloak-Installer#11]
**curl -o Cloak-Installer.sh -L https://git.io/fj5mh && bash Cloak-Installer.sh**
this link cloak version low，please update .
thinks.

**Comment by HirbodBehnam** [comment]
I uses the latest cloak version **released** that is 2.1.1. Also shadowsocks is always being downloaded from the repositories and nothing is build.
I'm not sure what do you exactly mean about _low version_.
