### ISSUE TITLE
How to change the RedirAddr？

### ISSUE THREAD

**Issue by windstander** [HirbodBehnam/Shadowsocks-Cloak-Installer#12]
It seems the script does not have the function to change the RedirAddr? Can you add this feature?

**Comment by HirbodBehnam** [comment]
Hello
Actually it does. When installing, it ask a question like this: `Please enter a redirection IP for Cloak`. You can enter it there.

**Comment by windstander** [comment]
No, I mean after installation, if I want to change the redirect IP, how to do it?

**Comment by HirbodBehnam** [comment]
You can change it by changing `/etc/cloak/ckserver.json`
But be aware that this might broke your client connections. (You need to update it on their config too)
