### ISSUE TITLE
No access after several hours!

### ISSUE THREAD

**Issue by cheshmghermezi** [HirbodBehnam/Shadowsocks-Cloak-Installer#13]
Hi there,
I used your script on a vps outside without a problem. Installed fine without a problem and was able to connect easy on my windows. So I setup a windows server vm from a-r-v-a-ncloud a-si-atech but it stopped working after 2-3 hours. I'm able to ping the ss server from windows vm and it shows connected but no data transfer.
It seems Iran DPI detects it.

**Comment by cheshmghermezi** [comment]
and this is not the ss server issue. because was able to connect to it from another loc.

**Comment by HirbodBehnam** [comment]
Hello
This script has nothing to do if it is a DPI problem. This repository is here to only install the Cloak server.
You can report it [here](https://github.com/cbeuw/Cloak/issues) if you like.
