### ISSUE TITLE
permission denied on ss-libev server

### ISSUE THREAD

**Issue by kagirun** [HirbodBehnam/Shadowsocks-Cloak-Installer#15]
@HirbodBehnam can you help me solve this please? im using debian 9

(ss-server)
● shadowsocks-libev.service - Shadowsocks-libev Default Server Service
   Loaded: loaded (/lib/systemd/system/shadowsocks-libev.service; enabled; vendo   Active: failed (Result: exit-code) since Thu 2019-11-28 19:19:27 PST; 7s ago
     Docs: man:shadowsocks-libev(8)
  Process: 3640 ExecStart=/usr/bin/ss-server -c $CONFFILE $DAEMON_ARGS (code=exi Main PID: 3640 (code=exited, status=255)

Nov 28 19:19:27 debian-s-4vcpu-8gb-sgp1-01 systemd[1]: Started Shadowsocks-libevNov 28 19:19:27 debian-s-4vcpu-8gb-sgp1-01 ss-server[3640]:  2019-11-28 19:19:27Nov 28 19:19:27 debian-s-4vcpu-8gb-sgp1-01 ss-server[3640]:  2019-11-28 19:19:27Nov 28 19:19:27 debian-s-4vcpu-8gb-sgp1-01 ss-server[3640]:  2019-11-28 19:19:27Nov 28 19:19:27 debian-s-4vcpu-8gb-sgp1-01 ss-server[3640]:  2019-11-28 19:19:27Nov 28 19:19:27 debian-s-4vcpu-8gb-sgp1-01 ss-server[3640]: Permission denied
Nov 28 19:19:27 debian-s-4vcpu-8gb-sgp1-01 systemd[1]: shadowsocks-libev.serviceNov 28 19:19:27 debian-s-4vcpu-8gb-sgp1-01 systemd[1]: shadowsocks-libev.serviceNov 28 19:19:27 debian-s-4vcpu-8gb-sgp1-01 systemd[1]: shadowsocks-libev.servicelines 1-16/16 (END)

(ck-server .json file)
{
  "ProxyBook": {
    "openvpn":["tcp","127.0.0.1:1984"] , "shadowsocks":["tcp","127.0.0.1:53809"$  },
  "BypassUID": [
    "",                                                     ""                                                    ],                                                                              "BindAddr":[":62112"],
  "RedirAddr": "204.79.197.200",
  "PrivateKey": "",
  "AdminUID": "",
  "DatabasePath": "/home/public/userinfo.db",                                     "StreamTimeout": 300
}

i already set permission to databasepath directory with this command:

chmod -R 777 /home/public

then i restart ck-server and it worked fine but whenever i start ss-server it says permission denied. 

here my ss-libev conf:
{                                                                                   "server":"127.0.0.1",
    "server_port":53809,
    "password":"",                                                            "timeout":60,                                                                   "method":"chacha20-ietf-poly1305",                                              "nameserver":"1.1.1.1",                                                         "plugin":"/etc/cloak",                                                          "plugin_opts":"/etc/cloak/ckserver.json"
} 

hope you can help me out. thanks!

**Comment by HirbodBehnam** [comment]
Hello
You should not define cloak in ss-libev config files.
Let the script completely handle the config files.
Reinstall the cloak and shadowsocks and next time do not change the config files.
