### ISSUE TITLE
Linux Client: pr_end_of_file_error when trying to browse

### ISSUE THREAD

**Issue by jike212** [HirbodBehnam/Shadowsocks-Cloak-Installer#18]
Thanks for putting together this script! Really helped me understand how Cloak and Shadowsocks work together.

The proxy is working well on Android however I'm having an issue with my Linux client. When running the command to start `ss-local` and setting my proxy settings, I get the error `pr_end_of_file_error` and I'm unable to view any websites.

The output in the terminal while I'm trying to browse looks like this:
```
INFO[0000] Listening on TCP 127.0.0.1:54329 for shadowsocks client 
INFO[0004] Attemtping to start a new session            
DEBU[0004] All underlying connections established       
INFO[0004] Session 1385539750 established               
DEBU[0034] attempting to actively close session 1385539750 
DEBU[0034] a connection for session 1385539750 has closed: read tcp 192.168.0.178:50048->xxx.xxx.xxx.xxx:443: use of closed network connection 
DEBU[0034] session 1385539750 closed gracefully
```

**Comment by HirbodBehnam** [comment]
Please report this issue at the Cloak repository issues.
