### ISSUE TITLE
Exit Code 255

### ISSUE THREAD

**Issue by MohammadGIV** [HirbodBehnam/Shadowsocks-Cloak-Installer#19]
I've been installed script on my server successfully and received ss:// connection too. In my Android device I've been installed shadowsocks official app with cloak plugin too. But i receive an error when I click connect button : 
libss-local exits too fast (exit code 255)
What should I do?

**Comment by HirbodBehnam** [comment]
Hello
At first, please send the ss link to me but cencore your server address and IP. (I just need to see if the link is valid or not)
Secondly make sure that you are using the latest cloak and shadowsocks version on android.
And if possible, try on another device or windows.

**Comment by qwerttvv** [comment]
https://github.com/cyqsimon/Cloak-android/releases/tag/v2.1.1.1

install that one

**Comment by MohammadGIV** [comment]
> Hello
> At first, please send the ss link to me but cencore your server address and IP. (I just need to see if the link is valid or not)
> Secondly make sure that you are using the latest cloak and shadowsocks version on android.
> And if possible, try on another device or windows.

ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNToxMjM0NQ==@[ServerIP]?plugin=ck-client%3BUID%3DAE4FgSM1guESeshSVvuCLFDDuLUXUg1%2FYdx5pjEGEL0%5C%3D%3BPublicKey%3DnAp65bsjKq2L2bRnu9MJxJeOduzRY8dmdVJgv%2FMScBk%5C%3D%3BServerName%3D[ServerIP]%3A443%3BTicketTimeHint%3D3600%3BMaskBrowser%3Dchrome%3BNumConn%3D4

**Comment by MohammadGIV** [comment]
> https://github.com/cyqsimon/Cloak-android/releases/tag/v2.1.1.1
> 
> install that one

I Did, not worked. 
About 1 month ago im installed cloak on my another server and worked. Today i installed cloak on my new server and i receiving this error. Problem seems to be server side, not client side.

**Comment by HirbodBehnam** [comment]
Is it working on windows or Mac OS?

**Comment by MohammadGIV** [comment]
> Is it working on windows or Mac OS?

Not tested yet, but i will. And what should i do for Android? as i said About 1 month ago im installed cloak on my another server and worked. Today i installed cloak on my new server and i receiving this error. Problem seems to be server side, not client side.

**Comment by HirbodBehnam** [comment]
I noticed that your `ss://` link is missing `StreamTimeout` and `EncryptionMethod` and includes `TicketTimeHint`. This means that you installed Cloak v1 instead of Cloak v2. Use the Cloak2-Installer script to install Cloak 2.
