### ISSUE TITLE
Plugin options imported with unneeded spaces between characters 

### ISSUE THREAD

**Issue by hybtoy** [HirbodBehnam/Shadowsocks-Cloak-Installer#2]
@HirbodBehnam 
Hey chief! Just tried your script, works like a charm, thanks. I am personally waiting for multi-user support. :)

After script finished, it provides with ss:// link, so we can import server to the client. 
On Android it is OK but on Windows when I am importing the server, in Plugin options of CK plugin in UID and Public Key fields there are unneeded spaces between characters. Because of that, client unable to connect to the server.

**Comment by HirbodBehnam** [comment]
Hello already reported the issue here:
https://github.com/shadowsocks/shadowsocks-windows/pull/2364
It's just a bug we shall wait.

Also I'm working at multiuser; It takes a lot of time so we just have to wait ;)

**Comment by HirbodBehnam** [comment]
Multi-user is added and I added a big note about windows bug.
So I'm closing this issue
