### ISSUE TITLE
Important Problem on Android client

### ISSUE THREAD

**Issue by MohammadGIV** [HirbodBehnam/Shadowsocks-Cloak-Installer#20]
Hi.
In cloak's android connection sometime after i connect to my server (and usually when i reach ~200MB data transfer) connection freezes and I should reconnect shadowsocks to fix the connection problem. In windows connection i don't experienced this problem yet. Also i don't set any limitations to my account in server.

**Comment by HirbodBehnam** [comment]
Report at main [cloak repository](https://github.com/cbeuw/Cloak)
