### ISSUE TITLE
Shadowsocks(libev) has updated several times, will this script also update?

### ISSUE THREAD

**Issue by windstander** [HirbodBehnam/Shadowsocks-Cloak-Installer#22]
Any way to install new version of Shadowsocks(libev) with this script?

**Comment by HirbodBehnam** [comment]
Hello
Unfortunately there is currently no way in script to build the shadowsocks libev.
If you want the lastest version, install the script, uninstall shadowsocks libev (from your package manager) and then build and install the shadowsocks libev from source. Finally, restart the server.
