### ISSUE TITLE
Display the QR code of the created user?

### ISSUE THREAD

**Issue by ayton** [HirbodBehnam/Shadowsocks-Cloak-Installer#23]
Thanks for the script, it works stably.
How to re-display the QR code of the created user on the server?

**Comment by HirbodBehnam** [comment]
Hello
Re-run the script and choose option 4 (Show Connections for Shadowsocks Users).
Select an UID and it will show you the qr code again.

**Comment by ayton** [comment]
Thanks for the quick response
