### ISSUE TITLE
add new rule problem

### ISSUE THREAD

**Issue by A2116** [HirbodBehnam/Shadowsocks-Cloak-Installer#25]
when I want to add new rule I have got these responses and unfortunately, ckserver.json completely erased

Please enter a number: 5
What do you want to do?
1) Add a rule
2) Delete a rule
Choose by number: 1
Where the traffic should be forwarded?(For example 127.0.0.1:6252) 127.0.0.1:49443
What should this be called? Clients must use this name as "ProxyMethod" on their computers: cloakovpn
jq: error: $k is not defined at <top-level>, line 1:
.ProxyBook += {$k}
jq: 1 compile error
Done

**Comment by HirbodBehnam** [comment]
Thanks for reporting!
I'll try to fix this by tomorrow.
