### ISSUE TITLE
cloak2 installer reset firewalld list

### ISSUE THREAD

**Issue by A2116** [HirbodBehnam/Shadowsocks-Cloak-Installer#26]
during installation script completely reset firewalld open ports
so, for example, ssh login to server become impossible
or any other service that runs on specific port becomes inaccessible

**Comment by HirbodBehnam** [comment]
Hello
What operating system?

**Comment by A2116** [comment]
centos7

**Comment by HirbodBehnam** [comment]
We're you using iptables before that? (Did the script overwrite the iptables rules?)

**Comment by A2116** [comment]
I do not change system defaults, everything is in its stock configuration

**Comment by HirbodBehnam** [comment]
Please note that in Centos 7, the script tries to install firewalld that probably overwrites the iptables rules.
If you are using iptables, do not install firewalld when scripts asks you if you want to install it or not.

**Comment by A2116** [comment]
the script does not ask for installation of centos 7

**Comment by HirbodBehnam** [comment]
If the firewalld is already installed, it will start it and add the cloak rules to it.

**Comment by HirbodBehnam** [comment]
Maybe I move the `systemctl start firewalld` to the block of code that installs it.
