### ISSUE TITLE
bad Show Connections for Shadowsocks Users information

### ISSUE THREAD

**Issue by A2116** [HirbodBehnam/Shadowsocks-Cloak-Installer#27]
when selecting Show Connections for Shadowsocks Users it shows me empty first password and encryption after your server IP address
also when scan qr-code shadowsocks program prompt me that encryption method not exist replace chacha20-ietf-poly1305 because Cloak Encryption is plain

**Comment by HirbodBehnam** [comment]
I cannot reproduce this problem.
Also you can change the encryption method when installing the shadowsocks.

**Comment by A2116** [comment]
where is the main password and encryption save? in which configuration file?
how I can change shadowsocks encryption after installation?
I change shadowsocks.json file but changes do not apply

**Comment by HirbodBehnam** [comment]
The config file is located at `/etc/shadowsocks-libev/config.json`.
Also you have to restart the `shadowsocks-libev` service to apply the changes to shadowsocks.

**Comment by A2116** [comment]
I have not such directory

**Comment by HirbodBehnam** [comment]
`systemctl status shadowsocks-libev`
Can you run this command and check if the shadowsocks is running?
Also do you have the directory `/etc/shadowsocks/`?

**Comment by A2116** [comment]
I identified the problem, it's because of low memory that during installation it does not install shadowsocks and skip it
I solve it by adding swap to the system

**Comment by HirbodBehnam** [comment]
Nice that you solved it!
Indeed, `yum` and `dnf` use alot of ram. lol
