### ISSUE TITLE
thanks you for adding feature multiuser

### ISSUE THREAD

**Issue by malikshi** [HirbodBehnam/Shadowsocks-Cloak-Installer#3]
what your recommended setting for every user with BW 40Mbps UP/DOWN? and can used for one devices

**Comment by HirbodBehnam** [comment]
Hello
At first keep in mind that you cannot limit admin's bandwidth and other stuff.
There is not general way to apply these limits to all users. You have to declare limits for each user individually. 
To limit connected devices, `SessionsCap` must be one.
If you want to limit all users to 40Mbit/s (That is 5 MB/s) you have to enter `5242880‬` as `UpRate` and `DownRate`. (**DO NOT COPY AND PASTE THIS NUMBER.**)
`UpCredit` and `DownCredit` is the upload and download limit for the user. 

To see the connection link and QR Code, re-run the script again and choose user management, then choose Show Connection Info for User and choose the user you wish to see his/her connection info.

**Comment by malikshi** [comment]
ok understand, is it bit or bytes i bit confused. what about upCredit for unlimited or says 2GB per user

**Comment by HirbodBehnam** [comment]
2 Gigabyte is `2147483648`‬ bytes  (**DO NOT COPY AND PASTE THIS NUMBER.**). 
For unlimited try `9223372036854775808‬`. This is 2^63 and max value of int64 in golang. [See here](https://github.com/cbeuw/Cloak/blob/master/cmd/ck-client/admin.go#L32).

**Comment by malikshi** [comment]
`Choose a username to continue:malik
Shadowsocks-Cloak-Installer.sh: line 113: [: malik: integer expression expected
Shadowsocks-Cloak-Installer.sh: line 113: [: malik: integer expression expected`
it first try before asking you. is it error because copy-paste when input UpRate DownRate and etc.

**Comment by HirbodBehnam** [comment]
No you should not do that. Choose a username by entering it's number. The line above that you can see list of usernames with a number behind it. Choose them by entering its number.

**Comment by malikshi** [comment]
its will make other bit confused about that, can you change it to this one?
> Choose a username by number to continue

**Comment by HirbodBehnam** [comment]
Yes I'm changing it right now.

**Comment by HirbodBehnam** [comment]
Done

**Comment by malikshi** [comment]
when script asking for username and expire time
can you add
>Multi Devices: as SessionCap
Upload Speed(Mbps): as UpRate
Download Speed(Mbps): as DownRate
Bandwidth Upload(GB): as UpCredit
Bandwidth Download(GB): as DownCredit

and showing that into after converting to format cloak server

>At first application wants you to enter the IP and Port of your server. Enter this:
127.0.0.1:443
Then you will be asked for Admin UID. Enter this:
e09UGsA7JcMjfsxM9BgNqL7sFdSFzmMNG6U2wMPJdFM=
Now you will enter the admin panel.
Type 4 at panel and press enter.
Enter p6lNC5UFhSGqFBQNkM1luzwD5Lf2cyaPafhB0xVA8gQ= as UID.
SessionsCap is result after converting multi devices
UpRate is ...
DownRate is  ...
UpCredit is ...
DownCredit is ...
For ExpiryTime, enter 1561345120
Then press Ctrl+C to exit admin panel

**Comment by HirbodBehnam** [comment]
I do not agree with this. Let the users do the calculation themselves. Some may need accurate speeds or etc.

**Comment by malikshi** [comment]
> I do not agree with this. Let the users do the calculation themselves. Some may need accurate speeds or etc.
> 
> Plus if I do this people will copy and paste. And also there is no to a little different if they multiply the numbers by 1000 instead of 1024.

okay i will close this issue,

**Comment by HirbodBehnam** [comment]
You're welcome
