### ISSUE TITLE
the effect of NumConn

### ISSUE THREAD

**Issue by A2116** [HirbodBehnam/Shadowsocks-Cloak-Installer#30]
what is the effect of NumConn=4?
is increasing it lead to better performance?
or the server becomes saturated?
what is the optimal range or number?

**Comment by HirbodBehnam** [comment]
Please read [here](https://github.com/cbeuw/Cloak#configuration) that all of the options of server and client are explained.
And I don't know the _optimal_ value of it; I just use 4 that is in the config samples in main cloak repository.

**Comment by A2116** [comment]
it says "Setting it too high will hinder the performance"
so I will test 4-8 for best results as for example firefox create 8 simultaneous connection
