### ISSUE TITLE
UDP is not supported?

### ISSUE THREAD

**Issue by rvpn** [HirbodBehnam/Shadowsocks-Cloak-Installer#31]
I have installed ss-cloak2 successfully, but upon further testing I can see UDP is not supported by checking it through this website https://networktest.twilio.com/

![Screenshot_2020-08-16-15-07-50-797_com android chrome](https://user-images.githubusercontent.com/28747439/90329167-dd795a80-dfd4-11ea-8880-44447036af82.jpg)

Is there any setting on the android client to solve this?

**Comment by HirbodBehnam** [comment]
Hello
Unfortunately, shadowsocks plugins does not support UDP at all. [Read The Restrictions Paragraph](https://shadowsocks.org/en/spec/Plugin.html)

**Comment by rvpn** [comment]
> Hello
> Unfortunately, shadowsocks plugins does not support UDP at all. [Read The Restrictions Paragraph](https://shadowsocks.org/en/spec/Plugin.html)

Owh tq sir for explaination.

Do you have any plan for your next project / scripts to support this feature be it trojan, v2ray or any other type of circumvention tools?

**Comment by HirbodBehnam** [comment]
Unfortunately I do not have any plans right now.
