### ISSUE TITLE
What’s the advantages of using Cloak?

### ISSUE THREAD

**Issue by NightMachinary** [HirbodBehnam/Shadowsocks-Cloak-Installer#38]
خود شدوساکس خالی هم در ایران کار می‌کنه، استفاده از کلوک چه مزیتی داره؟

**Comment by HirbodBehnam** [comment]
<div dir="rtl">
سلام

روی بعضی از سرور ها کار نمیکنه چون whitelist شدن.
cloak چون عملا میاد ترافیک رو شبیه https میکنه این whitelist رو رد میکنه.
روی یه سری از اینترنت ها هم روی ترافیک های غیر http throttling انجام میشه که با cloak اینم اوکی میشه
</div>
