### ISSUE TITLE
Can't generate new QR codes

### ISSUE THREAD

**Issue by mfat** [HirbodBehnam/Shadowsocks-Cloak-Installer#39]
After installation I re-run the script to generate new QR codes, but the script just creates new user IDs. How can I generate new ss:// links or QR codes?
Thanks a million for this script.

**Comment by HirbodBehnam** [comment]
Hello
You can choose `Show Connections for Shadowsocks Users` option when you re-run the script to create the QR Code and the `ss://` links again for specific users.
