### ISSUE TITLE
cloak doesnt support TFO?

### ISSUE THREAD

**Issue by malikshi** [HirbodBehnam/Shadowsocks-Cloak-Installer#4]
im tried edit your script with small adjustment to actived TFO and bbr in one script, (only ubuntu 18.04 or higher).
everything script work, but when `ShowConnectionInfo` i am got spaces withingss url.

**Comment by HirbodBehnam** [comment]
Hello
At first what is TFO?
Then, if you are using windows client that's a but that will be fixed in next version.

**Comment by malikshi** [comment]
> Hello
> At first what is TFO?
> Then, if you are using windows client that's a but that will be fixed in next version.

TFO is tcp fast open
here my config sysctl
>fs.file-max = 51200
net.core.rmem_max = 67108864
net.core.wmem_max = 67108864
net.core.netdev_max_backlog = 250000
net.core.somaxconn = 4096
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 30
net.ipv4.tcp_keepalive_time = 1200
net.ipv4.ip_local_port_range = 10000 65000
net.ipv4.tcp_max_syn_backlog = 8192
net.ipv4.tcp_max_tw_buckets = 5000
net.ipv4.tcp_fastopen = 3
net.ipv4.tcp_mem = 25600 51200 102400
net.ipv4.tcp_rmem = 4096 87380 67108864
net.ipv4.tcp_wmem = 4096 65536 67108864
net.ipv4.tcp_mtu_probing = 1
net.ipv4.conf.all.forwarding=1
net.ipv6.conf.all.forwarding=1
net.core.default_qdisc=fq
net.ipv4.tcp_congestion_control=bbr

**Comment by HirbodBehnam** [comment]
Oh yes I tested fast open too where was some problems with it.

**Comment by malikshi** [comment]
> Oh yes I tested fast open too where was some problems with it.
> It's a good idea to open an issue about this on the main Cloak repository.

yea, i will do that,

can you remove ufw installation if not going used in your script. ?

**Comment by HirbodBehnam** [comment]
UFW is used as the firewall in Ubuntu. Why remove it?

**Comment by malikshi** [comment]
> UFW is used as the firewall in Ubuntu. Why remove it?

but is it still working, not even active?
you should added `ufw enable`  ?

**Comment by HirbodBehnam** [comment]
Won't UFW enable automatically when installed?

**Comment by malikshi** [comment]
> Won't UFW enable automatically when installed?

i think its should be enable so all traffic will be through ufw firewall

**Comment by HirbodBehnam** [comment]
Ok I will enable it on my next commit.
Thanks for reporting 👍

**Comment by malikshi** [comment]
please testing it first. i will make commit there after done with my scripting sir.

**Comment by malikshi** [comment]
testing it first sir. cheers

**Comment by HirbodBehnam** [comment]
Thanks for reporting that bug about firewall I will fix that tomorrow.
Also if you like I can add an option to ask the user if he/she wants to enable BBR on Ubuntu 18

**Comment by malikshi** [comment]
> Thanks for reporting that bug about firewall I will fix that tomorrow.
> Also if you like I can add an option to ask the user if he/she wants to enable BBR on Ubuntu 18

yups its will be good. still waiting cloak next version h3h3h3

**Comment by HirbodBehnam** [comment]
OK I added BBR and also a softer firewall checker to even ask user if he/she wants to install firewall if not available. If you want other stuff in my script do not hesitate to open a pull request or issue.
