### ISSUE TITLE
Option to update user restrictions

### ISSUE THREAD

**Issue by resuls** [HirbodBehnam/Shadowsocks-Cloak-Installer#40]
Currently, I can either `add` or `remove` users but cannot update the restrictions I set earlier. Is there any way to do it?

**Comment by HirbodBehnam** [comment]
Hello
Currently because of the Cloak limitations this not possible. It only accepts add and delete operations as taken from [here](https://github.com/cbeuw/Cloak-panel/blob/master/script/endpoint.js)
