### ISSUE TITLE
Fail to install shadowsocks-libev

### ISSUE THREAD

**Issue by kreslando** [HirbodBehnam/Shadowsocks-Cloak-Installer#42]
![bug](https://user-images.githubusercontent.com/12049395/159150683-49fdac29-f1b4-4c5d-b4f7-48448e29b624.PNG)
I'm not sure how to fix it. Help, please. Thank you.

**Comment by HirbodBehnam** [comment]
Hello
I cannot reproduce this problem on Centos 7.8
Can you try `yum install ca-certificates` and try again?
