### ISSUE TITLE
Connecting two servers with cloak 2

### ISSUE THREAD

**Issue by KourosZanbouri** [HirbodBehnam/Shadowsocks-Cloak-Installer#44]
First of all, @HirbodBehnam thank you for this amazing script ;)

I have two ubuntu servers ( Server 1and Server 2), And I want to tunnel Server 1 through server 2 with cloak plugin
The goal is to connect to S2 ( 192.168.0.5 ) through S1 (192.168.1.1) : client > S1 > S2 

How should I config the rules?

**Comment by HirbodBehnam** [comment]
Hello thanks!
You can chain two Cloak connections like so:
Client connects to a bare metal Cloak server 1 which is installed on S1. This server forwards it's incoming traffic on port A of S1 (loop-back connection). A Clock _client_ must be running on S1 as well which accepts connections from port A of it's localhost and forwards them to loopback port B on S2. Port B on S2, must be binded by the application which you want to send traffic to.
HOWEVER, there is an easier way. Setup Cloak server on S2 and do whatever you want with it's rules. Let's say that Cloak on S2 listens on port C. All you have to do is to forward traffic on port D of S1 to port C of S2. When configuring your client, just use S1:D as the destination address.
You can read about TCP forwarding from here or Google:
https://serverfault.com/a/140626
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/security_guide/sec-port_forwarding

**Comment by KourosZanbouri** [comment]
Thank you for your guidance
