### ISSUE TITLE
Extreme conditions

### ISSUE THREAD

**Issue by hawshemi** [HirbodBehnam/Shadowsocks-Cloak-Installer#45]
Is cloak being blocked?
I created some servers and cloaked them up with a script. They were working flawlessly with minimal speed/latency change.
But suddenly, they are not connecting. Client sending data but not receiving any!
Is there a way to fix this issue now that we are in extreme conditions in Iran while it's actively blocking VPN protocols?
Do you have any script installer for vmess or trojan ?

**Comment by HirbodBehnam** [comment]
Hello
I don't know if it's being blocked or not. Mine at least is working fine. Also, you can try changing the browser fingerprint from chrome to firefox or vice versa in the plugin settings. That might help you.
And I don't have any scripts for v2ray or trojan. Might write one in future tho...

**Comment by hawshemi** [comment]
I changed the signature from chrome to firefox, and it's working!
Could you tell me why this happened? so I can be prepared for future blockings?
Also, do you have any suggestions for VPS companies? (for setting up shadowsocks or other kinds of protocols)

**Comment by HirbodBehnam** [comment]
I don't really know why it happens but apparently changing the fingerprint to Firefox fixes the problem.
For VPS companies, I use [virmach](https://virmach.com/).

**Comment by hawshemi** [comment]
Thanks for all the help.
Hope we will hear from you with new scripts :D
