### ISSUE TITLE
"Message size greater than buffer" error

### ISSUE THREAD

**Issue by dimqua** [HirbodBehnam/Shadowsocks-Cloak-Installer#6]
I'm getting the following error:
```
INFO: connect to github.com:443
ERROR: Failed to prepare connection to remote: Reading TLS message: message size greater than buffer. message size: 7304
```
I'm running OpenWRT and using shadowsocks-libev with ck-client-linux-mips_softfloat-2.0.2 plugin.

Any idea how can I fix this problem?

**Comment by HirbodBehnam** [comment]
Hello
Does this happens while using the script (installing or changing users)?
Or this is a message happens in clock server service log?

**Comment by dimqua** [comment]
No, this is an output of `ck-client`, my server isn't running openwrt. :-) Should I address this issue to the upstream then?

**Comment by dimqua** [comment]
The problem was that I used a wrong installer script (for Cloak v1).
